### ISSUE TITLE
Add example of how to test a kubebuilder project

### ISSUE THREAD

**Issue by crandles** [kubernetes-sigs/e2e-framework#109]
kubebuilder leverages [envtest](https://book.kubebuilder.io/reference/envtest.html) in the test suite it generates with its scaffold infrastructure for creating kubernetes controllers. `envtest` is not a full kubernetes cluster, so some complex controller implementations are unable to be tested using the tooling without mocks.

The existing envtest has a basic usage that should be easily supported by this framework:
```go
// By default, kubebuilder implements this (via scaffolding) using the Ginkgo suite.

import sigs.k8s.io/controller-runtime/pkg/envtest

//specify testEnv configuration
testEnv = &envtest.Environment{
    CRDDirectoryPaths: []string{filepath.Join("..", "config", "crd", "bases")},
}

//start testEnv
cfg, err = testEnv.Start()

//write test logic

//stop testEnv
err = testEnv.Stop()
```

To simplify usage, an `envfunc` helper (or just an implementation of the types.EnvFunc interface) should be added to simplify the crd install / uninstall (using the `decoder` package).

Alternatively: import and inter-op with the [envtest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest) implementation installing CRDs and webhooks.

**Comment by vladimirvivien** [comment]
@crandles this would be awesome.
I vote for an envfunc (maybe in the third_party directory, since kubebuilder is external)

**Comment by vladimirvivien** [comment]
With #135 merging, this should be supported now.
