### ISSUE TITLE
E2E framework does not supported with GKE.

### ISSUE THREAD

**Issue by dhadukk** [kubernetes-sigs/e2e-framework#111]
Our CI pipeline on GKE is failing with error ,
panic: envconfig: client failed: no Auth Provider found for name "gcp"
log link : https://runway-ci.eng.vmware.com/teams/mdogra/pipelines/gke-e2e/jobs/e2e-testsuite/builds/8.

In order to fix this, _import "k8s.io/client-go/plugin/pkg/client/auth/gcp"_ needs to be added.

I am happy to contribute to the project and fix this, but I am not sure which files do I need to add above import.

**Comment by harshanarayana** [comment]
Did you try adding an import for this in your test code itself right before you invoke the e2e-framework handlers ? (This should get things working for you to unblock your workflow)

```go
_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```

There are a few different [auth plugin](https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth/) handlers that are provided by client-go by default  other than `gcp`

But looking at the code shows that `gcp` plugin is getting deprecated in favor of `gcloud` and `azure` one in favor of their own exec based plugin. Wonder if we can just enable the `exec` plugin support at the framework level and let the end users of framework decide how they want to use the auth plugin. The in-tree one with `_` import or the exec mode.

**Comment by vladimirvivien** [comment]
I think third party auth libraries such as gcp and azure and others should be explicitly added by the test writer.  The framework should not be automatically load these libraries as each use case may be different.

@dhadukk please let us know if adding the package import yourself works for you. If not, let us know why what we can do to help.

**Comment by dhadukk** [comment]
Thank you @vladimirvivien and @harshanarayana
I will add the import in testfile itself and update here.

**Comment by dhadukk** [comment]
Fix added in the test file. It works fine. Thank you.
