### ISSUE TITLE
TestInParallel feature not working as expected

### ISSUE THREAD

**Issue by dapdelivery** [kubernetes-sigs/e2e-framework#119]
Although the features are getting executed in parallel, but the assess written within those features are getting mixed up with other features in parallel execution.

e2e-framework version used: **v0.0.6**

**Ex:**
Feature1 -> assess1
Feature2 -> asses2
When we try to run them parallel, it executes the following
	feature1 -> assess2
	feature2 -> assess2

**Sample code:**

//go:build all || dummy

package install_tests

import (
    "context"
    "fmt"
    "os"
    "testing"

    "sigs.k8s.io/e2e-framework/pkg/env"
    "sigs.k8s.io/e2e-framework/pkg/envconf"
    "sigs.k8s.io/e2e-framework/pkg/features"
    "time"
)

var (
    clusterName string
    namespace   string
    testEnv     env.Environment
)

func TestMain(m *testing.M) {

    cfg, _ := envconf.NewFromFlags()
    testEnv = env.NewWithConfig(cfg)

    os.Exit(testEnv.Run(m))
}

func TestParallelRuns(t *testing.T) {
    featureOne := features.New("Feature One").
        Assess("Assess 1", func(ctx context.Context, t *testing.T, config *envconf.Config) context.Context {
            println(fmt.Sprintf("feature1-Assess1, datetime: %s", time.Now().String()))
            time.Sleep(10 * time.Second)
            return ctx

        }).Feature()

    featureTwo := features.New("Feature Two").
        Assess("Assess 2", func(ctx context.Context, t *testing.T, config *envconf.Config) context.Context {
            time.Sleep(2 * time.Second)
            println(fmt.Sprintf("feature2-Assess2, datetime: %s", time.Now().String()))
            return ctx
        }).Feature()

    testEnv.TestInParallel(t, featureOne, featureTwo)

}

**Execution cmd:** go test . -v -timeout 240m -count=1 -tags=dummy -args --parallel

**Execution output:**

=== RUN   TestParallelRuns
=== RUN   TestParallelRuns/Feature_Two
=== RUN   TestParallelRuns/Feature_Two/Assess_2
=== RUN   TestParallelRuns/Feature_One
=== RUN   TestParallelRuns/**Feature_One/Assess_2**
**feature2-Assess2**, datetime: 2022-03-16 18:06:37.489844 +0530 IST m=+2.009548369
**feature2-Assess2**, datetime: 2022-03-16 18:06:37.48979 +0530 IST m=+2.009494100
--- PASS: TestParallelRuns (2.00s)
    --- PASS: TestParallelRuns/Feature_Two (2.00s)
        --- PASS: TestParallelRuns/Feature_Two/Assess_2 (2.00s)
    --- PASS: TestParallelRuns/Feature_One (2.00s)
        --- PASS: TestParallelRuns/Feature_One/Assess_2 (2.00s)
PASS
ok      gitlab.eng.vmware.com/tap/tap-packages/suite/dummy      2.479s

**NOTE**: Notice that the Assess_2 is not part of Feature_One but is executed under it.

**Comment by ShwethaKumbla** [comment]
Thanks for filing the issue @dapdelivery. We will look into it.

/cc @harshanarayana

**Comment by harshanarayana** [comment]
```go
for i, feature := range testFeatures {
		featName := feature.Name()
		if featName == "" {
			featName = fmt.Sprintf("Feature-%d", i+1)
		}
		if runInParallel {
			wg.Add(1)
			go func(w *sync.WaitGroup) {
				defer w.Done()
				e.processTestFeature(t, featName, feature)
			}(&wg)
		} else {
			e.processTestFeature(t, featName, feature)
		}
	}
```
Goofup on my part here. Need a 

`feature := feature` in the loop
