### ISSUE TITLE
Add example related to get access real k8s cluster

### ISSUE THREAD

**Issue by Lxrdknows77** [kubernetes-sigs/e2e-framework#124]
All examples regarding work with cluster related to creating kind cluster in Setup. But can you also add at least 1 example how to use it with KUBECONFIG file because it's not clear. Thanks.

**Comment by Lxrdknows77** [comment]
I figured it out, but still not clear there is some alternative to get config or create env from $HOME/.kube/config ? 
Something like `config.GetConfig()` from **"sigs.k8s.io/controller-runtime/pkg/client/config"** package.

**Comment by harshanarayana** [comment]
Did you try using the `ResolveKubeConfigFile()` helper ?

```go
import (
     "sigs.k8s.io/e2e-framework/klient/conf"
)

.....
     path = conf.ResolveKubeConfigFile()
```

xref: https://github.com/kubernetes-sigs/e2e-framework/blob/cd133e286ac7059c7743561cb6441542d60674f4/klient/conf/config.go#L67
