### ISSUE TITLE
Register cluster API types

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes-sigs/e2e-framework#126]
When trying to interact with clusterAPI objects like:
```
var cluster v1beta1.Cluster
err := cfg.Client().Resources("").List(context.TODO(), &cluster)
```
you get the error
```
no kind is registered for the type v1beta1.Cluster in scheme "pkg/runtime/scheme.go:100"
```

We should register clusterAPI types by default in the library since this is a common (and great) use case.

**Comment by johnSchnake** [comment]
Duplicate of #104

**Comment by Lxrdknows77** [comment]
I solved it by adding <NewKind>.AddToScheme(scheme.Scheme)

**Comment by johnSchnake** [comment]
Yea; I want to make sure its just a non-issue for those going forward. Its frustrating because that one line is pretty much all you need to do to make it work, but to test it you have to get clusterctl and run `clusterctl init` which just adds time to everything. I think its important we can test that though for any future issues with clusterAPI related work.

**Comment by Lxrdknows77** [comment]
Understood. I guess it also will more tricky when you use more than 1 third part Api types.
