### ISSUE TITLE
Add reference to Golang library reference

### ISSUE THREAD

**Issue by karuppiah7890** [kubernetes-sigs/e2e-framework#130]
https://pkg.go.dev/sigs.k8s.io/e2e-framework or https://pkg.go.dev/github.com/kubernetes-sigs/e2e-framework 

The reference can be added in the readme as a link and also as a badge, like this - 

[![godoc](https://pkg.go.dev/badge/github.com/sigs.k8s.io/e2e-framework)](https://pkg.go.dev/sigs.k8s.io/e2e-framework)

The markdown for this is below

```markdown
[![godoc](https://pkg.go.dev/badge/github.com/sigs.k8s.io/e2e-framework)](https://pkg.go.dev/sigs.k8s.io/e2e-framework)
```

**Comment by karuppiah7890** [comment]
cc @ShwethaKumbla @vladimirvivien

**Comment by vladimirvivien** [comment]
Thanks @karuppiah7890 great idea.
