### ISSUE TITLE
Support Cloud Providers

### ISSUE THREAD

**Issue by helayoty** [kubernetes-sigs/e2e-framework#131]
As a developer, I want to be able to spin up a managed kubernetes cluster from well-known providers i.e. AKS, ESK, GKE

**Comment by vladimirvivien** [comment]
@helayoty thanks for the issue.
The framework offers `EnvFunc` types so that test developers can extend their tests.  Regardless, I agree it would be useful to use `EnvFunc`s to stand up popular providers.  The code could be hosted in `third-party` dir to minimize dependency.

**Comment by vladimirvivien** [comment]
@helayoty you may be interested in issue #132

**Comment by helayoty** [comment]
@vladimirvivien fyi https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2163

**Comment by vladimirvivien** [comment]
Sweet! @helayoty .
We should revisit this soon to show how easy it is to drive kubetest2 providers from e2e-framework tests.

**Comment by vladimirvivien** [comment]
This issue should be revisited at a future time. My one concern here is keeping up with the evolution/changes in how each provider stand up their cluster. There is work going on to integrate kubetest2 with the e2e-framework (see https://github.com/kubernetes-sigs/e2e-framework/pull/168). This would allow test writers to externalize/delegate cluster deployment to kubetest2.

**Comment by vladimirvivien** [comment]
Hi @helayoty 
Now that the e2e-framework supports running tests with kubetest2, can this be closed ?

**Comment by helayoty** [comment]
@vladimirvivien  YES. Thanks for making that happen!
