### ISSUE TITLE
Implement a `kubetest2 tester` for e2e-framework

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/e2e-framework#132]
This is a marker issue to indicate that this project should have a [Kubetest2](https://github.com/kubernetes-sigs/kubetest2)  tester implemented. Kubetest2 can stand up an environment and/or lunch tests. It has several providers implemented including kind, gce, etc. 

Adding a kubetest2 tester would allow this project to delegate environment startup/tear down to kubetest2 and reuse existing providers.  I propose that the implementation be contributed to the kubetest2 project to make it easy to build/run. 

Test writers who are looking to adopt kubetest2 can use this project to write tests and use the kubetest2 binary to launch the test similar to the following:

```
kubetest2 kind -v 2 \
  --up \
  --down \
  --test=e2e-framework \
  --assess='boombap'
  --skip-assessment='network'
```

**Comment by tyxeron** [comment]
This would be super nice. We are currently looking for an end-to-end test framework to test our k8s setup. How far up the road would you guess this feature is? Is there currently a workaround for this?

**Comment by vladimirvivien** [comment]
Hi @tyxeron  there is currently no one immediately working on this. It's mostly a nice to have since the e2e framework provides its own programmatic way of managing test lifecycles including the ability to launch external environments. 

Please take a look at the examples for ways of running end-to-end tests using code that can launch kind as part of the test lifecycle. While kind is the only env that is inherently supported, the api is easy to support any env.

Hope that helps

**Comment by vladimirvivien** [comment]
See https://github.com/kubernetes-sigs/kubetest2/pull/218
