### ISSUE TITLE
Release version 0.0.7

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/e2e-framework#136]
This issue is to track the release of version 0.0.7

### Extended Feature test API 
The feature test type now supports arbitrary name for all steps allowing for better parsing of test results

```go
func TestHello_WithSetup(t *testing.T) {
	e := env.NewWithConfig(envconf.New())
	var name string
	feat := features.New("Hello Feature").
		WithLabel("type", "simple").
		WithSetup("SetupName", func(ctx context.Context, t *testing.T, _ *envconf.Config) context.Context {
			name = "foobar"
			return ctx
		}).
		Assess("test message", func(ctx context.Context, t *testing.T, _ *envconf.Config) context.Context {
			result := Hello(name)
			if result != "Hello foobar" {
				t.Error("unexpected message")
			}
			return ctx
		}).WithTeardown("Teardown", func(ctx context.Context, t *testing.T, _ *envconf.Config) context.Context {
                ...
		}).Feature()

	e.Test(t, feat)
}
```

### Fix: Parallel test scoping
This release introduces a fix for a race condition that was causing data overwrites when running feature tests in parallel. 

### Testing of custom resources (CRDs)
This release provides enhancements to the `klient` package to register arbitrary resource schemes. This allows test writers to create tests for arbitrary resources such as custom resources.

### Other improvements
* Improved Github Actions
* Automation using `goreleaser`

**Comment by ryanemerson** [comment]
When will `0.0.7` be released?

**Comment by vladimirvivien** [comment]
@ryanemerson 0.0.7 is coming this week. I decide to delay to allow one more feature to land.
Thanks for checking.
