### ISSUE TITLE
Panic prevents cleanup cycle in `Finish`

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/e2e-framework#141]
I have a simple test that starts kind  in `Setup` and destroy the cluster in `Finish`. 

```go
func TestMain(m *testing.M) {
	cfg, _ := envconf.NewFromFlags()
	testEnv = env.NewWithConfig(cfg)
	kindClusterName = envconf.RandomName("test-", 16)
	namespace = envconf.RandomName("my-ns", 10)

	testEnv.Setup(
		envfuncs.CreateKindCluster(kindClusterName),
		envfuncs.CreateNamespace(namespace),
	)

	testEnv.Finish(
		envfuncs.DeleteNamespace(namespace),
		envfuncs.DestroyKindCluster(kindClusterName),
	)

	os.Exit(testEnv.Run(m))
}
```
However, if there is a panic during test execution, the `Finish` environment functions are not executed.

It would be great if the framework recovered from panics and still execute the `Finish` block.

**Comment by harshanarayana** [comment]
@vladimirvivien  I like the idea of this. However, can we wrap this in an argument flag to let end users decide if they want this enabled or not? If the `Finish` is tearing down clusters, it might better to let it panic and fail without running the `Finish` handlers. Right ?

**Comment by vladimirvivien** [comment]
@harshanarayana I like your proposed arg name. I appreciate the concern that people may already be dependent on the existing behavior. However, I think it's an error if users rely on panic to skip cleanup. That intent should be done with an argument as you pointed out.

**Comment by harshanarayana** [comment]
> I think it's an error if users rely on panic to skip cleanup.

That is how errors become features 😉  That being said, I am fine with the option you suggested. Let me get a PR going. By default it will recover from the panic. And we provide a way to ignore and bypass the finish for whatever reason the user might want to do so

**Comment by adabuleanu** [comment]
@harshanarayana / @vladimirvivien thanks for this feature. Is this worth extending this so that in case of a panic occurrence during setup/assessment methods of a test the [test teardown ](https://github.com/harshanarayana/e2e-framework/blob/main/pkg/env/env.go#L314-L318) can run? My use case is that I always want to perform cleanup on my tests even if panic occurs.
