### ISSUE TITLE
Enh Proposal: Feature Flag support

### ISSUE THREAD

**Issue by harshanarayana** [kubernetes-sigs/e2e-framework#144]
## Requirement

There are a good amount of new features that are being discussed in the Issue thread of this repo that needs a detailed design document to be put in place. This made me wonder if there is a need to provide a set of feature flags for this repo that can be enabled/disabled to ensure certain new behaviours are disabled if they are still experimental when running tests on production. 

## Examples/Use Case
xref: #138 and #133 

The above two issues are good example of the required changes. Both of those will need additional APIs to be introduced in order to be able to support some of the features being asked for / discussed. However, not everyone might want to use them right out of the gate. It would be great to have a way to enable/disable these features via a CLI argument adhering to the k/k feature flag convention to make it easy to avoid users running into unwanted confusion. 

## Proposal

1. Add a new CLI flag named `--feature-flags` that can be used to enable/Disable a feature in question
2. Set the New features to `false` by default and move them to `true` after qualifying them to stable from experimental
3. A `pkg/featureflags` package that can be used to control the feature-flag behaviors
    1. Helper function to check if a feature is enabled/disabled
    2. Helper function to programatically toggle a feature flag
    3. Enumerated set of features to re-user
    4. A helper function to integrate with `pflag` 

What do you guys think ? cc @vladimirvivien  @ShwethaKumbla

**Comment by vladimirvivien** [comment]
@harshanarayana agreed. 
I would also suggest looking around other Kubernetes project to get inspiration on their feature management.

**Comment by vladimirvivien** [comment]
@harshanarayana  can this one be close
