### ISSUE TITLE
Enhancement: Able to get controller-runtime Client from the Resources

### ISSUE THREAD

**Issue by dmvolod** [kubernetes-sigs/e2e-framework#146]
In most of the cases, we need to get and utilize controller-runtime Client internally for the intermediate functions
It would be nice to have a functions GetClient() inside the `klient/k8s/resources/resources.go` to get controller-runtime Client for this case.
Alternatively, we could probably have a helper function in the `klient` package returning Client as
```golang
cr.New(c.cfg, cr.Options{Scheme: scheme.Scheme})
```

**Comment by dmvolod** [comment]
Hi @vladimirvivien 
Thanks for response. Our case is: we have a set of the helpers methods (lookup for default StorageClass, some PVC logic, etc.) in our controllers utilising controller-runtime Client and would like to reutilize part of them inside the e2e-framework tests to reduce the codebase. For example we should skip test if default StorageClass not allows to extend a volume size.

**Comment by harshanarayana** [comment]
@dmvolod  Is this not what you are looking ?

https://github.com/kubernetes-sigs/e2e-framework/blob/e93ce38fcf9c53e1bd89c0c7a6e8949bd92fbc69/klient/k8s/resources/resources.go#L51-L70

**Comment by harshanarayana** [comment]
> For example we should skip test if default StorageClass not allows to extend a volume size.

```golang
Assess("Do Something", func(ctx context.Context, t *testing.T, c *envconf.Config) context.Context {
			r, err := resources.New(c.Client().RESTConfig())
			if err != nil {
				t.Fail()
			}
			var sc v1.StorageClass
			err = r.Get(ctx, "test", "", &sc)
			if err != nil && errors.IsNotFound(err) {
				t.Skip("No tests are there is missing storage class")
			}
			if sc.AllowVolumeExpansion == nil || !*sc.AllowVolumeExpansion {
				t.Skip("Skipping test as the volume expansion is not allowed")
			}
			// Do something
			return ctx
		}).
```

What you are looking for can be achieved this way too.

**Comment by dmvolod** [comment]
Thanks, @harshanarayana , I know how to do this, but we have a dozens of functions and don't won't to repeate code of them in the tests instead of just provider one parameter with the cr.Client

**Comment by harshanarayana** [comment]
I see. So 

> Are you looking for a way to access the resources.client outside via a getter ?

this is what you are looking for ?

**Comment by dmvolod** [comment]
> Are you looking for a way to access the `resources.client` outside via a getter ?

Yes, exactly, @harshanarayana , missed your first comment.

**Comment by vladimirvivien** [comment]
@dmvolod can you provide a code snippet of what you are doing with the controller-client once you get it? I ask because that can be useful functionality worth adding directly in the framework itself. 

How are you using the client to detect StorageClass enabled ? Or is it the fact that you have existing code that you don't want to change and exposing the client would make integration easier ?

**Comment by Lxrdknows77** [comment]
Hi @vladimirvivien 

In our kubernetes operator, we use a dedicated struct to provide all parameters to iterate with the k8s cluster. One of these parameters is controller-runtime Client **cr client.Client**:

```
type k8sCluster struct {
	Client                client.Client
	Scheme                *runtime.Scheme
	Logger                logr.Logger
	Object                client.Object
	...                  ...
}
```

And as @dmvolod said before we also have a lot of functions (based on native k8s controller-runtime client functions like Get(), List() etc.).  

And also we have a method to validate StorageClass Volume Expansion that uses cr client.Client:
```
func (g *ShootCluster) IsAllowVolumeExpansion(storageClass *storagev1.StorageClass) bool {
	return !(storageClass.AllowVolumeExpansion == nil || (storageClass.AllowVolumeExpansion != nil && !*storageClass.AllowVolumeExpansion))
}
```
Thus, to test this (and another) method in our e2e tests we have to re-implement them all in accordance with your klient.Klient client instead if just import our package and use it as it is. 

Much better would be have helper function something like @dmvolod mention above: 
`cr.New(c.cfg, cr.Options{Scheme: scheme.Scheme}`to reuse this function in our integration test just to provider **contriller-runtime Client** parameter to our k8sCluster struct.
And it will let us just call our function in e2e tests.
```
k8sCluster.IsAllowVolumeExpansion(storageClass)
```

**Comment by vladimirvivien** [comment]
I think this is a good suggestion and exposing the controller-runtime client does not break the current API.

**Comment by harshanarayana** [comment]
@vladimirvivien  @Lxrdknows77 @dmvolod  I have a draft PR with two ways of fetching the controller runtime client. TPAL when time permits.

**Comment by harshanarayana** [comment]
@Lxrdknows77 Yes and also lets you inject your own custom `runtime.Scheme` for any uses that might arise.

**Comment by Lxrdknows77** [comment]
@harshanarayana Will you fix it or I can recreate PR?

**Comment by harshanarayana** [comment]
@Lxrdknows77  Sorry, this one totally skipped my list of TODO items. Please feel free to recreate the PR. If you can wait until end of the week, I will have the PR ready

**Comment by vladimirvivien** [comment]
@harshanarayana Have you gotten a chance to finalize this so we can merge?

**Comment by harshanarayana** [comment]
@vladimirvivien  I have already update the PR https://github.com/kubernetes-sigs/e2e-framework/pull/156 with some of the comments addressed.
