### ISSUE TITLE
support running all tests in parallel

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/e2e-framework#17]
the k/k framework uses ginkgo which has [parallel mode (-p)](https://onsi.github.io/ginkgo/) for tests that were not explicitly defined as "parallel". this allows running the whole suite in parallel with N workers.

while tests in this framework can use t.Parallel() to opt-in into parallel execution, perhaps it would be possible to override that and run all tests in parallel, unless certain tests are "serial only".

the k/k framework does have have the `[Serial]` tag for that and users of the parallel mode can skip them with `-skip`.

**Comment by vladimirvivien** [comment]
This is a great suggestion and will be investigated in future improvement cycles.
Thanks!
