### ISSUE TITLE
Expect permutations

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/e2e-framework#18]
Would be cool if we could do pytest style `xfails` or ExpectFails of some sort , i.e. 

1) Write a test
2) be able to specify that you expect it to fail at runtime 
3) pass a test suite even though some failures happened because of inputs to (2)

**Comment by vladimirvivien** [comment]
Good for pointing this out. I think it's a good idea.
Future round of improvements will include features such as these.
