### ISSUE TITLE
correct way to use this with gke after auth plugin deprecation

### ISSUE THREAD

**Issue by willfindlay** [kubernetes-sigs/e2e-framework#186]
Now that `k8s.io/client-go/plugin/pkg/client/gcp` is deprecated, what's the correct way to use e2e-framework with GKE clusters? The package complains about a missing auth plugin for `gcp` when I attempt to use e2e-framework with the `k8s.io/client-go/plugin/pkg/client/auth` import removed.

**Comment by vladimirvivien** [comment]
Hi @willfindlay thank you for pointing that out. Is there any suggestion out there how to use client-go with gcp, now that it is deprecated? Can you post a link that discuss how to handle the deprecation? This will be something worth fixing.

**Comment by willfindlay** [comment]
Hi @vladimirvivien this is the page that is linked from the deprecation warnings: https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

**Comment by vladimirvivien** [comment]
@willfindlay the code (rightly so) makes no assumption about any providers. So even with the deprecation changes you pointed out, it should still work (as long as you specify your provider plugin in the test).  Take a look at this example https://github.com/kubernetes-sigs/e2e-framework/tree/main/examples/real_cluster and let me know if that gets you going OK. If not, please provide more info where your code is failing.

**Comment by willfindlay** [comment]
Thanks, it's possible I was doing something else wrong here. Let's close this for now and I'll re-open if needed.
