### ISSUE TITLE
Add `--context` flag

### ISSUE THREAD

**Issue by maruina** [kubernetes-sigs/e2e-framework#187]
It would be great to be able to pass a `--context` flag to protect against running the tests in the wrong cluster.

I can see this useful when you might switch context in a different shell and then re-running the tests or to make sure to run the tests against a specific cluster.

I would be happy to raise the PR if you think this feature might be useful.

**Comment by vladimirvivien** [comment]
It may be worth looking into exposing Kubernetes flags from the CLI-runtime project to handle most common cluster flags (https://github.com/kubernetes/cli-runtime).

**Comment by vladimirvivien** [comment]
@maruina no worries, if you think you may want to take on that as a PR, I am here to help.

**Comment by harshanarayana** [comment]
This would be a good addition to have. But we might have to think of a few cases

1. How will this fit in along with the `--kubeconfig` argument
2. If one were to setup unique  `kubeconfig` for each of their test run + cluster combination, the context is not really required as the `--kubeconfig` should be able to handle the requirement
3. How does this work when the new cluster is being created with the `kind` based setup ? The context passed here will be the cluster context for the newly created kind cluster ?
4. Do we have to now consider checking the actual context is valid or not before using it ?

**Comment by maruina** [comment]
Hey @harshanarayana, thanks for your input. I think we can:
1. Follow the kubectl behaviour, where you can pass both flags, none or one or the other
2. Yes, you are correct. If you have a single context in the kubeconfig then you don't need this. In my case I have multiple contexts and when running the test I want to make sure I'm targeting the desired cluster
3. If you're not passing a context I would assume you use the current context, so there should be no changes for when you create a kind cluster
4. When you use the wrong context in kubectl you get
```
❯ kubectl --context foo get pods
Error in configuration: context was not found for specified context: foo
```
so I would just error when we try to use it. I don't know if we can make any checks when we use `clientcmd`

What do you think?
