### ISSUE TITLE
e2e-framework project documentation site

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/e2e-framework#192]
Contributors of this project work hard to provide documentation with new functionalities (see the ./example dir). However, the project does not have a centralized location that gathers and curates the documentation for newcomers.  

As a user of this project, I would like a single location where feature documentation is curated and organized into a subdirectory or a separated project site (or both). That way newcomers can quickly find answers and this would help with adoption.

**Comment by harshanarayana** [comment]
@vladimirvivien  This is definitely going to be useful. How do we propose we start with this ? First have everything organized into subdirectories and then slowly get a site up and running ?

**Comment by vladimirvivien** [comment]
@harshanarayana Yes. We can re org the ./docs directory (move design under design) and then start putting feature docs there.

**Comment by harshanarayana** [comment]
Works for me. Let me get a PR up with re-organizing the docs and examples.

**Comment by harshanarayana** [comment]
```bash
❯ ls                                                                                                                                                                                                                                                                                    20%  ▓▒░
README.md design    features
❯ tree .
.
├── README.md
├── design
│   ├── README.md
│   └── e2e-environment-design.png
└── features
    ├── dry-run-mode.md
    ├── fail-fast-mode.md
    ├── k8s-resource-watcher.md
    ├── klient-package.md
    └── resource-decoding.md

2 directories, 8 files
❯ pwd
/k8s-dev/e2e-framework/docs
```

@vladimirvivien  does this look like a good start? I will rename the files and add a few more files to some of the feature that we have examples for under the examples dir.

**Comment by vladimirvivien** [comment]
@harshanarayana I would suggest keeping it even flatter (as show below). If we need to a special directory in the feature for something else, then we can create a new dir. For now, all feature docs can go inside /doc.

```
❯ tree .
.
├── README.md
├── design
│   ├── README.md
│   └── e2e-environment-design.png
├── dry-run-mode.md
├── fail-fast-mode.md
├── k8s-resource-watcher.md
├── klient-package.md
└── resource-decoding.md
```

**Comment by vladimirvivien** [comment]
@harshanarayana anything on this? Do you want to take on this? If not let me know. I would like to have some docs for the next release in the next couple of weeks.

**Comment by harshanarayana** [comment]
I will have a PR for you to look at in a day or two.. Sorry got a bit held up with some office work.. Haven't been able to spend time on if.

**Comment by vladimirvivien** [comment]
@harshanarayana No worries.
