### ISSUE TITLE
How to specify multiple labels when running tests

### ISSUE THREAD

**Issue by embano1** [kubernetes-sigs/e2e-framework#194]
This example recommends a label key `test` and values for individual features:

https://github.com/kubernetes-sigs/e2e-framework/blob/8e4361f050f28ea6dc55e8885a14f7d66dd4d45a/README.md?plain=1#L70-L84

However, following this logic, I cannot run multiple features with the same label `key`, e.g. 

`--labels="feature=feat1,feature=feat2"` is not possible (in my current tests the first one is ignored). I guess this is due to the label parsing map used:

https://github.com/kubernetes-sigs/e2e-framework/blob/8e4361f050f28ea6dc55e8885a14f7d66dd4d45a/pkg/flags/flags.go#L290

Wondering if we should fix this so I can run multiple features instead of just one when using the same label `key`.

**Comment by vladimirvivien** [comment]
@embano1 thanks for the issue. Are you saying that a features cannot have multiple labels added to it? Or are you saying you just want to run multiple features with the same labels ? 

For the latter, you should be able to declare multiple features with the same labels and run them:

```go
func TestHello_WithSetup(t *testing.T) {
	e := env.NewWithConfig(envconf.New())
	var name string
	f0 := features.New("Hello Feature").
		WithLabel("type", "hello").
		Assess("test message", func(ctx context.Context, t *testing.T, _ *envconf.Config) context.Context {
			result := Hello(name)
			if result != "Hello foobar" {
				t.Error("unexpected message")
			}
			return ctx
		}).Feature()

	  f1 := features.New("Goodbye Feature").
		WithLabel("type", "message").
		Assess("test message", func(ctx context.Context, t *testing.T, _ *envconf.Config) context.Context {
			result := Goodbye(name)
			if result != "Goodbye foobar" {
				t.Error("unexpected message")
			}
			return ctx
		}).Feature()
	e.Test(t, f0, f1)
}
```
You should be able to select each feature by label as follows:

```
go run . -args --labels="type=hello, type=goodbye"
```

If i completely misunderstood your question, please let me know.

**Comment by embano1** [comment]
Thx for your response! What I found was that if `featureX` had label `"feature=foo"` and `featureY` had the label `"feature=bar` if I run `go run . -args --labels="feature=foo,feature=bar"` only `featureY` ran. Looking up the code, it seems a map is used which would overwrite labels with the same key i.e. `"feature`.
