### ISSUE TITLE
Expose `TestEnvFunc` similarly as it's done with `FeatureEnvFunc` and `EnvFunc`

### ISSUE THREAD

**Issue by pmalek** [kubernetes-sigs/e2e-framework#199]
Currently `FeatureEnvFunc` and `EnvFunc` are exposed in https://github.com/kubernetes-sigs/e2e-framework/blob/main/pkg/env/env.go#L37-L41 to alias the underlying internal types.

This unfortunately is not being done for `TestEnvFunc`.

One can work around this simply by defining it on their own:

```
type TestEnvFunc = func(context.Context, *envconf.Config, *testing.T) (context.Context, error)
```

but it doesn't feel right.

This would be beneficial to e.g. allow end users mapping step funcs to test funcs

```
type TestEnvFunc = func(context.Context, *envconf.Config, *testing.T) (context.Context, error)

func IntoTestEnvFunc(stepFn features.Func) TestEnvFunc {
	return func(ctx context.Context, e *envconf.Config, t *testing.T) (context.Context, error) {
		return stepFn(ctx, t, e), nil
	}
}
```

### Proposed solution

Expose `TestEnvFunc`.

**Comment by harshanarayana** [comment]
@pmalek I think exposing it won;t be that big of a problem. But before we do that, we can see if there is a better way to do what you are trying to achieve. With that in mind, would you mind providing a bit more context and possibly an example of what you are trying to do ?

**Comment by pmalek** [comment]
I was thinking about converting e.g. `TestEnvFunc` into `FeatureEnvFunc` or vice versa where the context of a feature if important for a particular function. Something similar to the snippet in the description.

**Comment by vladimirvivien** [comment]
@pmalek This is an interesting idea. But as @harshanarayana mentioned, I would like to see an actual example where this would help. I agree that maybe we need `TestEnvFunc` exposed as a type:

```go
type TestEnvFunc = func(context.Context, *envconf.Config, *testing.T) (context.Context, error)
```
But I am not clear why the conversion is needed. Are you interested in re-using those pre-defined EnvStepFuncs from within a test itself ?

**Comment by pmalek** [comment]
> But I am not clear why the conversion is needed. Are you interested in re-using those pre-defined EnvStepFuncs from within a test itself ?

The use case I had a while ago was to reuse the "common" step/testenv funcs by adapting one to another, e.g. when I'd need to create a namespace and store it in `context.Context` I don't need 2 separate functions to do so. It's enough to adapt one to another and not use all the parameters. This is handy in cases where the tests that end user tries to write do are not your typical tests, e.g. requiring namespace creating on different levels, not only on test but also on assessment level.

Does that make sense?

**Comment by vladimirvivien** [comment]
@pmalek Yes. I see the merit of the use case. I reviewed the code to make sure there is no design flaw in the way we are doing things that is causing your need.  I think for now, we are OK and we can just expose type `TestEnvFunc` in package `env` as:

```go
type (
	Environment = types.Environment
	Func        = types.EnvFunc
	FeatureFunc = types.FeatureEnvFunc
        TestFunc    = types.TestEnvFunc
)
```

@harshanarayana let me know what you think.

**Comment by pmalek** [comment]
This should do it #210. Thanks
