### ISSUE TITLE
Investigate Go v1.20 `-skip` flag

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/e2e-framework#200]
[Go 1.20](https://tip.golang.org/doc/go1.20) introduces the `-skip` flag for `go test` command to skip tests based on name patterns. This feature should be (at the very least) documented and show how to use it along with the `--skip-*` flags supported by e2e-framework.

**Comment by reetasingh** [comment]
I would like to work on this issue
/assign

**Comment by vladimirvivien** [comment]
@reetasingh thank you!

**Comment by reetasingh** [comment]
@vladimirvivien where do we want this to be documented ?
In the README.md ?

**Comment by vladimirvivien** [comment]
@reetasingh For now, let's put in ./examples/skip_flags. Just add a section documenting that tests can also be skipped using the new `go test -skip` flag to show differences.
