### ISSUE TITLE
Support for using Kubernetes-SIGs Kwok cluster simulator

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/e2e-framework#214]
#### Proposal
[kwok](https://kwok.sigs.k8s.io/) is a Kubernetes cluster simulator, from Kubernetes-SIGs, that can start fully Kubernetes API-compatible cluster. This project should investigate how e2e-framework can leverage Kwok for end-to-end testing. Currently, the project already has environment functions that can start/stop Kind.  It would be useful to create environment functions to start/configure/stop kwok clusters at test time for quickstart end-to-end tests.

The following is an illustrative mock up of what that support could look like. This example would create a simulated cluster, run the tests, then teardown that cluster.

```go
func TestMain(m *testing.M) {
	testenv = env.New()
	clusterName := envconf.RandomName("some-cluster", 16)
	namespace := envconf.RandomName("kind-ns", 16)

	testenv.Setup(
		envfuncs.CreateKwokCluster(kindClusterName),
		envfuncs.CreateNamespace(namespace),
	)

	testenv.Finish(
		envfuncs.DeleteNamespace(namespace),
		envfuncs.DestroyKwokCluster(kindClusterName),
	)
	os.Exit(testenv.Run(m))
}
```

#### References
* Kwok - https://kwok.sigs.k8s.io/
* Kwok Github - https://github.com/kubernetes-sigs/kwok

**Comment by reetasingh** [comment]
@ vladimirvivien I am interested in working on this feature.

**Comment by wzshiming** [comment]
I am happy to see that the e2e-framework will support kwok 🎉🎉🎉

I have a small requirement, I want to [refactor e2e] for kwok/kwokctl with e2e-framework, and I need e2e-framework to be able to support modifications to the kwokctl dependency version, rather than the [kind version].

[refactor e2e]: https://github.com/kubernetes-sigs/kwok/issues/423
[kind version]: https://github.com/kubernetes-sigs/e2e-framework/blob/06323f44a3a104d0c9e2be4d18b356810c6fc8ed/support/kind/kind.go#L31

**Comment by harshanarayana** [comment]
@wzshiming  The kind version is configurable too. Just that it also defaults to a specific version

https://github.com/kubernetes-sigs/e2e-framework/blob/06323f44a3a104d0c9e2be4d18b356810c6fc8ed/support/kind/kind.go#L45-L48

```golang
cluster := kind.NewCluster(name)
cluster.WithVersion("0.24.0")
kubeconfig, err := cluster.Create()
// do things after
```

**Comment by wzshiming** [comment]
> @wzshiming The kind version is configurable too. Just that it also defaults to a specific version
> 
> https://github.com/kubernetes-sigs/e2e-framework/blob/06323f44a3a104d0c9e2be4d18b356810c6fc8ed/support/kind/kind.go#L45-L48
> 
> ```go
> cluster := kind.NewCluster(name)
> cluster.WithVersion("0.24.0")
> kubeconfig, err := cluster.Create()
> // do things after
> ```

Thank you, I see!

**Comment by reetasingh** [comment]
@vladimirvivien @ wzshiming I have opened https://github.com/kubernetes-sigs/e2e-framework/pull/239 for this feature. please review. My apologies for delay in sending a PR

**Comment by wzshiming** [comment]
@vladimirvivien 
I am in the process of writing e2e, I didn't find that `sigs.k8s.io/e2e-framework/klient/k8s/resources` has a method to update subresources(status), which is essential for kwok e2e, is it possible to add this.

**Comment by vladimirvivien** [comment]
@wzshiming Absolutely 👍   Please open a PR for contribution.
