### ISSUE TITLE
Testing changes locally with a local registry for a controller?

### ISSUE THREAD

**Issue by Skarlso** [kubernetes-sigs/e2e-framework#217]
Hello! I'm not a 100% sure if I understood this correctly, but... If I read this right, this framework can only be used as a clutch to create and apply Kubernetes objects and create the cluster, right? It doesn't help with building the changes locally and pushing them into a local registry to apply the right thing to the cluster? If I want to test a controller for example...

I would have to do something before-hand, like building and pushing to a local registry and somehow making the change available for this test infra to use for the deployment? How would that work?

**Comment by harshanarayana** [comment]
> his framework can only be used as a clutch to create and apply Kubernetes objects and create the cluster, right

Not necessarily. This framework can be used to do what you said for sure. But it also has the ability to stand up a simple kind cluster to use as a base for your tests to be run, it also has ability to connect to a real cluster to run tests against them directly. 

>  It doesn't help with building the changes locally and pushing them into a local registry to apply the right thing to the cluster

You can do that as well. But you have to code that into your test code itself. The test env has a `.Setup` handler that you can use to perform the required test setup actions. Which in this case can be building and deploying the controller code to the cluster. Along with Installing the CRDs and others. 

> I would have to do something before-hand, like building and pushing to a local registry and somehow making the change available for this test infra to use for the deployment?

You can do this as well. This will work just fine. 

> How would that work?

1. Build your controller and deploy to your cluster (if you are using operator-sdk kind of infra, it becomes easy to do that using a single `make` command. If not, you have to use whatever your regular toolings are)
2. Get the Kube Config file from the cluster where the controller is deployed
3. Run the tests using the e2e-framework by hooking your test harness against the cluster where the controller is deployed using the kubeconfig from step 2

```golang
var testEnv env.Environment

func TestMain(m *testing.M) {

	cfg, err := envconf.NewFromFlags()
	if err != nil {
		log.Fatalf("failed to load env config: %s", err)
	}

	testEnv = env.NewWithConfig(cfg)
	testEnv.Setup(func(ctx context.Context, c *envconf.Config) (context.Context, error) {
		curDir, err := os.Getwd()
		if err != nil {
			return ctx, err
		}
		os.Chdir("/path-to-controller-code")
		// Do the Controller Build and deployment here using make ccommands for example
		if err := exec.Command("make install").Run(); err != nil {
			return ctx, err
		}
		os.Chdir(curDir)
		return ctx, nil
	})
	os.Exit(testEnv.Run(m))
}
```

Something like above can be used as well to build and deploy the component to the cluster directly.

**Comment by Skarlso** [comment]
Yeah, I moved beyond this. I actually built an amalgamation using e2e-framework here for steps based testing + Tilt to setup multiple controllers at the same time using the local changes. Which can just as well run on a ci environment.

And all you have to do is run `go test ./...` and the rest is done for you. :) 

Here is it -> https://github.com/controller-e2e-framework/e2e-framework

So you don't have to worry about building anything yourself or shell out to `make install` and some such. :) tilt is pretty cool it works really well together with this framework. :)

**Comment by harshanarayana** [comment]
That's wonderful @Skarlso

**Comment by Skarlso** [comment]
Also, thank you, this is an amazing framework. I really love it. I will do some meetup appearances and talk about this. :) Cheers for the help @harshanarayana! :))

**Comment by Skarlso** [comment]
Also, thank you, this is an amazing framework. I really love it. I will do some meetup appearances and talk about this. :) Cheers for the help @harshanarayana! :))

**Comment by Skarlso** [comment]
Also, thank you, this is an amazing framework. I really love it. I will do some meetup appearances and talk about this. :) Cheers for the help @harshanarayana! :))
