### ISSUE TITLE
Execute "testenv.Finish" even when test panics

### ISSUE THREAD

**Issue by dapdelivery** [kubernetes-sigs/e2e-framework#219]
Currently we observe that "testenv.Finish" does not execute when the test ("testenv.Test") has a panic.
Ideally, we want the testenv.Finish to execute regardless of test status (almost like a finally block of code in python) since we have cleanup written in this code block. 

Also,  is there a plan to add "BeforeTest" and "AfterTest" in the framework (not referring to BeforeEachTest or AfterEachTest) and the requirement would be "AfterTest" executes regardless of the test status as well.

**Comment by pranavb23** [comment]
Could you elaborate a bit more on what the difference between Before/AfterTest and Before/AfterEachTest would be?

**Comment by vladimirvivien** [comment]
@harshanarayana this sounds like we need some recover logic to catch hard panics (not just testing.Fatal)

**Comment by vladimirvivien** [comment]
A fix here may also be a fix for  #188

**Comment by matrus2** [comment]
@dapdelivery It would be nice if you could provide a simple example of this use case.

**Comment by adabuleanu** [comment]
I confirm that if you get panic inside a test it will not run the `testenv.Finish`. In this case there is no way of running any cleanup when a panic occurs.
