### ISSUE TITLE
Enhancement: Define Cluster Provider Interfaces for ease of extension

### ISSUE THREAD

**Issue by harshanarayana** [kubernetes-sigs/e2e-framework#245]
Until recently, the e2e framework had just one way to create a local cluster and that was using `kind`. 

However, with the changes that @reetasingh  has been working on for https://github.com/kubernetes-sigs/e2e-framework/pull/239, there is now `kwok` support. This bring up a point that there is not a standard interface that defines the cluster provider (We should also find a suitable name for this. Cluster provider might not be the right one) so that we can easily extend the `envfunc` without having to duplicate them for each of the clusters. 

This started in the discussion of the above PR under https://github.com/kubernetes-sigs/e2e-framework/pull/239#discussion_r1168259000

```golang
type clusterOpts func(c ClusterProvider)

type ClusterProvider interface {
	WithVersion(version string) ClusterProvider
	WithOpts(opts ...clusterOpts) ClusterProvider
	Create(args ...string) (string, error)
	GetKubeConfig() string
	GetKubectlContext() string
	ExportLogs(dest string) error
	Destroy() error
	LoadDockerImages(image string) error
	LoadImageArchive(archivePath string) error
}
```

Above is a possible example of what the interface might look like (This is in no way the what we want to use eventually but just for the same of discussion). 

Defining above will help us do a few things. 

1. Parameterise the `envfuncs` helpers for `kind/kwok` so that they are just one set of functions and and invoked via the interface types 
2. It also lets extend this easily in the future to add additional provides such as `k3s` or `kubeadm` for example

**Comment by harshanarayana** [comment]
@vladimirvivien  @reetasingh  @ShwethaKumbla  I have a Draft PR opened to continue the discussion further on this work. PTAL when possible.

**Comment by reetasingh** [comment]
> @vladimirvivien @reetasingh @ShwethaKumbla I have a Draft PR opened to continue the discussion further on this work. PTAL when possible.

@harshanarayana thanks, overall LGTM. definitely makes adding a new provider much more seamless.
