### ISSUE TITLE
Fixed client-go version cannot support older k8s versions

### ISSUE THREAD

**Issue by helayoty** [kubernetes-sigs/e2e-framework#267]
Currently, the `e2e-framework` Dependabot automatically pins to the latest `client-go`. While this is great to have the framework up-to-date, it might be a hassle when it comes to supporting multiple Kubernetes versions. 

Is there a way to customize the version? Is it possible to get the version during the runtime, not in the compile time?

**Comment by harshanarayana** [comment]
@helayoty  Is that even possible in the golang world ? I believe we do not have any hard dependency on the client-go version really. So, end users can always pin the version to a suitable one using go mode rewrite way. It should work just fine so long as the client-go versions are compatible with each other. 

If this is not what you had in mind, would you happen to have an example of what you are thinking about in terms of what this could look like ?
