### ISSUE TITLE
Allow execution of non-feature tests

### ISSUE THREAD

**Issue by crandles** [kubernetes-sigs/e2e-framework#268]
Support the execution of tests without requiring use of the [features](https://pkg.go.dev/sigs.k8s.io/e2e-framework@v0.2.0/pkg/features) package.

To the [Environment](https://github.com/kubernetes-sigs/e2e-framework/blob/v0.2.0/pkg/internal/types/types.go#L49-L88) interface, I propose the addition of two new functions:

```go
type Environment interface {
	RunTest(ctx context.Context, t *testing.T, cfg *envconf.Config) bool
	RunBenchmark(ctx context.Context, b *testing.B, cfg *envconf.Config) bool
}
```

I am unsure what if anything makes sense as return values, [t.Run](https://pkg.go.dev/testing?utm_source=godoc#T.Run) returns a bool which may fit here; additionally `RunBenchmark` might deserve its own issue, given the current lack of support overall for benchmarks.

Note, there is some overlap in wording with this existing function, unsure if the above naming will be confusing:
```go
	// Run Launches the test suite from within a TestMain
	Run(*testing.M) int
```

The goal is to allow a more stream-lined path to writing go tests natively or otherwise with the framework of choice; don't force usage of the features package.

Potential usage:
```go
testenv.RunTest(ctx context.Context, t *testing.T, cfg *envconf.Config) (context.Context, error){
  ...
  if err != nil {
    t.Fatal(err)
  }
  ...
   t.Run("...", func(t testing.T){
     t.Parallel()
     ...
   })

})
```

**Comment by harshanarayana** [comment]
@crandles  https://github.com/kubernetes-sigs/e2e-framework/issues/133 We kind of sort of dig into the idea of running Benchmark workflows. But didn't manage to get it ahead. I would love to see that being picked up again. it would be a wonderful addition

**Comment by vladimirvivien** [comment]
This may still be something we need to check out 
cc @crandles @harshanarayana 

/remove-lifecycle rotten

**Comment by vladimirvivien** [comment]
/remove-lifecycle stale

I like the idea of offering a light way of launching feature tests.

**Comment by crandles** [comment]
Started to look into this again

* The simplest option seems to be to allow accessing the environment config: https://github.com/kubernetes-sigs/e2e-framework/pull/451
* I explored adding a `RunTest` helper that called the same underlying helper functions as `Test`, so that the before/after helpers ran -- and this works -- but without further code modifications, the feature/assesment concepts still leak through test names (if feature name is empty, it is rendered as `Feature-1`, assessment as `Assessment-1`, etc)
* benchmark helpers would need a whole new suite of functions, as `testing.T` is used throughout the current set of functions

**Comment by vladimirvivien** [comment]
@crandles this sounds awesome. Yes, this framework did not have benchmark in mind, but would be a great addition.  This is exciting, can't wait to see how this turns out.
