### ISSUE TITLE
Execute "testenv.Finish" steps in a reverse order

### ISSUE THREAD

**Issue by sagikazarmark** [kubernetes-sigs/e2e-framework#269]
When preparing a test environment in a `MainTest` function it probably looks something like this:

```go
// Create cluster
testenv.Setup(envfuncs.CreateKindCluster(clusterName))
testenv.Finish(envfuncs.DestroyKindCluster(clusterName))

// Install some additional dependency
testenv.Setup(installSomeDependency)
testenv.Finish(uninstallSomeDependency)
```

Unfortunately, in this case the KinD cluster will be destroyed first before getting to any other finish hooks. Right now the fix is moving finish steps to the end of the function:

```go
// Create cluster
testenv.Setup(envfuncs.CreateKindCluster(clusterName))

// Install some additional dependency
testenv.Setup(installSomeDependency)
testenv.Finish(uninstallSomeDependency)

// Delete cluster
testenv.Finish(envfuncs.DestroyKindCluster(clusterName))
```

It becomes even worse when you allow using a real cluster in your tests:

```go
var createCluster bool
clusterName := envconf.RandomName("vault-secrets-webhook-test", 32)

// Set up cluster
if os.Getenv("USE_REAL_CLUSTER") == "true" {
	path := conf.ResolveKubeConfigFile()
	cfg := envconf.NewWithKubeConfig(path)

	testenv = env.NewWithConfig(cfg)
} else {
	createCluster = true

	testenv.Setup(envfuncs.CreateKindCluster(clusterName))
}

// Install some additional dependency
testenv.Setup(installSomeDependency)
testenv.Finish(uninstallSomeDependency)

if createCluster {
	testenv.Finish(envfuncs.DestroyKindCluster(clusterName))
}
```

It really hurts readability. One potential solution would be adding a flag to execute Finish steps in a reverse order (or introduce a new type of step that does the same).

**Comment by sagikazarmark** [comment]
Here is a very simple workaround:

```go
type reverseFinishEnvironment struct {
	env.Environment

	finishFuncs []env.Func
}

// Finish registers funcs that are executed at the end of the test suite in a reverse order.
func (e *reverseFinishEnvironment) Finish(f ...env.Func) env.Environment {
	e.finishFuncs = append(f[:], e.finishFuncs...)

	return e
}

// Run launches the test suite from within a TestMain.
func (e *reverseFinishEnvironment) Run(m *testing.M) int {
	e.Environment.Finish(e.finishFuncs...)

	return e.Environment.Run(m)
}
```

**Comment by harshanarayana** [comment]
@sagikazarmark 

> Unfortunately, in this case the KinD cluster will be destroyed first before getting to any other finish hooks. Right now the fix is moving finish steps to the end of the function:

Why is that unfortunate ? The setup and tear down sequence are left to the consumers. Is it really correct to make an assumption that the finish should always be executed in the reverse order of how they are called ?

Both `testenv.Setup` and `testenv.Finish` take an array of handler functions as input. So you can always order them in the way you want them to be executed in without the framework having to make any assumption.  Is there a benefit in executing the steps in reverse order for `.Finish`?  Would it be right to make that assumption at all ?

> It becomes even worse when you allow using a real cluster in your tests:

How does reversing the order of execution of `Finish` going to help resolve this issue ? 

You could do something like following?

```golang
	testenv.Setup(
		func(ctx context.Context, c *envconf.Config) (context.Context, error) {
			if _, ok := os.LookupEnv("USE_REAL_CLUSTER"); ok {
				c = c.WithKubeconfigFile(conf.ResolveKubeConfigFile())
			} else {
				return envfuncs.CreateKindCluster(kindClusterName)(ctx, c)
			}
			return ctx, nil
		},
                installSomeDependency
	)
	testenv.Finish(
                uninstallSomeDependency,
		func(ctx context.Context, c *envconf.Config) (context.Context, error) {
			if _, ok := os.LookupEnv("USE_REAL_CLUSTER"); ok {
				return envfuncs.DestroyCluster(kindClusterName)(ctx, c)
			}
			return ctx, nil
		},
	)
```
The conditional check though is not the best way. It would be really nice to have an optional conditional function that we can pass along with each step so that, before the steps are invoked, the conditional function is called and if it return true then only the rest of the setup is invoked. That can really simplify these conditional workflows.

**Comment by sagikazarmark** [comment]
@harshanarayana I believe I presented a few examples demonstrating the problem and why I believe having the _option_ to run finish steps in a reverse order could be valuable.

> Is it really correct to make an assumption that the finish should always be executed in the reverse order of how they are setup ?

I don't claim it is. I presented a few cases where it would make sense to have it as an option.

>  Is there a benefit in executing the steps in reverse order for .Finish?

Once again, I believe that I demonstrated a case for that. I would imagine Finish to behave similarly to how you would call `defer` (or more specifically to tests: how `t.Cleanup` works).

> How does reversing the order of execution of Finish going to help resolve this issue ?

By mimicking the behavior of `defer` and `t.Cleanup` you could call `Finish` right after `Setup` keeping the cleanup code close to the original setup. I really can't make a better argument than that, since it's a pattern already widely used in Go.


> The conditional check though is not the best way. It would be really nice to have an optional conditional function that we can pass along with each step so that, before the steps are invoked, the conditional function is called and if it return true then only the rest of the setup is invoked. That can really simplify these conditional workflows.

The whole point behind my suggestion is to improve readability. I don't think adding predicates to the story is necessary.

I simply want to use existing patterns when using this framework and improve readability.

**Comment by vladimirvivien** [comment]
I think this is still worth exploring. Keeping it open (cc @sagikazarmark @harshanarayana )

/remove-lifecycle rotten

**Comment by harshanarayana** [comment]
@vladimirvivien  what about we use the other discussion on feature flag to control this so that we can retain the current behavior and not break the backward compatibility and enable this feature for those who are interested in using it ?
