### ISSUE TITLE
Support explicitly specifying which CLI binaries to invoke

### ISSUE THREAD

**Issue by negz** [kubernetes-sigs/e2e-framework#282]
The e2e-framework offers packages to help spin up Kind clusters and install Helm charts. These packages wrap the `kind` and `helm` CLI tools. (There may be other wrapped CLI tools but I haven't encountered them yet.)

The framework seems to look for these tools with hardcoded binary names (`kind`, `helm`) in `$PATH`. If `kind` isn't available the framework attempts to install it using `go install`. If `helm` isn't available the framework returns an error.

In @crossplane our `Makefile` handles installation of tools like Kind and Helm, but it doesn't install them in `$PATH`. We can probably hack around this when running the E2E tests (e.g. add a dir to `$PATH` and symlink to the tools from that dir) but it would be ideal to be able to pass the path to the binaries as flags.

**Comment by negz** [comment]
As a side note, it would also be useful to debug log which binaries are being used.

**Comment by harshanarayana** [comment]
I missed taking care of a few items on the previous PR. Need to update a few more bits and then this can be closed.
