### ISSUE TITLE
WithStep level argument, defined `Levels` are private

### ISSUE THREAD

**Issue by phisco** [kubernetes-sigs/e2e-framework#288]
As per the title, I noticed the [WithStep](https://github.com/kubernetes-sigs/e2e-framework/blob/15e91144243aab9c611f5706c3e7c48ceb881850/pkg/features/builder.go#L42) accepts a `Level` as argument, but the actual levels are only declared in an internal package and not publicly exposed, https://github.com/kubernetes-sigs/e2e-framework/blob/15e91144243aab9c611f5706c3e7c48ceb881850/pkg/internal/types/types.go#L105, is this intentional?

I would have liked to use `WithStep` to distinguish `Assessment`s with side-effects from Assessments only doing actual assessments. Not really a blocker, obviously.

**Comment by harshanarayana** [comment]
@phisco  Sorry for taking a bit to respond back to this. Entirely missed responding back to this. 

I think it should be ok to expose the Level values outside of the internal package alone. @vladimirvivien  do you have any concerns on doing that ?

**Comment by phisco** [comment]
No problem, wasn't really a blocker for us in the end, just a nice to have.

**Comment by vladimirvivien** [comment]
@phisco Missed the original post. Thanks for pointing that out. 
Originally, levels were meant as an internal mechanism to distinguish the different steps.
Now that more folks are using the framework, if it's useful to access that info at runtime, I am not against that.

**Comment by phisco** [comment]
Awesome! I'll open a PR later today 👍
