### ISSUE TITLE
Unused testenv.rnd

### ISSUE THREAD

**Issue by phisco** [kubernetes-sigs/e2e-framework#290]
Looking around I noticed [testenv.rnd](https://github.com/kubernetes-sigs/e2e-framework/blob/15e91144243aab9c611f5706c3e7c48ceb881850/pkg/env/env.go#L48) is not copied over when "cloning" the testenv via [WithContext](https://github.com/kubernetes-sigs/e2e-framework/blob/15e91144243aab9c611f5706c3e7c48ceb881850/pkg/env/env.go#L128) function, but looking further turns out rnd is not actually used anywhere.
Looking at the history rnd was added by @vladimirvivien as part of #55, but the only usage was then removed to address some review comment, so I guess it could be removed and there is no reason to "fix" `WithContext` to clone it over instead.

**Comment by vladimirvivien** [comment]
@phisco Thanks for pointing that out. You are welcome to open a PR so we can take care of it.

**Comment by vladimirvivien** [comment]
I don't recall why it was added. It is possible that field is not needed.
