### ISSUE TITLE
re-org Framework package structure to avoid import cycles under tests 

### ISSUE THREAD

**Issue by harshanarayana** [kubernetes-sigs/e2e-framework#293]
@harshanarayana I am coming back here so it doesn't fall the radar. `decoder_test`  means our dependency graph has an issue. Let's open a PR (if you haven't done so) for package re-org to avoid this situation.

_Originally posted by @vladimirvivien in https://github.com/kubernetes-sigs/e2e-framework/pull/246#discussion_r1248849162_

**Comment by reetasingh** [comment]
Hi @harshanarayana @vladimirvivien I am interested in working on this issue. can you add more description to this?
