### ISSUE TITLE
What does this repo aim at?

### ISSUE THREAD

**Issue by liubog2008** [kubernetes-sigs/e2e-framework#3]
- A replacement of `k8s.io/kubernetes/test/e2e/framework`
- An operator test framework
- A generic e2e framework
- Others

I'm finding a e2e framework to avoid importing `k8s.io/kubernetes` in my project.

BTW: status of this repo? any future plan?

**Comment by cpanato** [comment]
Hello, @liubog2008 thanks for opening this issue, let me try to answer your question and apologizes in advance if did not answer all.

The idea of this repo is to produce a framework that will make it easier for consumers to use that and not have the need to import the `k8s.io/kubernetes/test/e2e/framework` which today is hard to do.

Maybe in the future, we replace the existing k8s e2e with this one, but this is not the focus at this moment.

@vladimirvivien is doing some base work to bootstrap this project and he already some PR in draft mode in place but needs some changes.

Also, I think we will start some discussions and create issues to split the work and get this project on the road. So be patient a bit 😄

**Comment by liubog2008** [comment]
I  am interested in this repo. How to join you ?

**Comment by vladimirvivien** [comment]
Please find the design doc for this repo here - https://docs.google.com/document/d/11JKqcnUOrw5Lk98f_ylJXBXyxWSW1z3CZu27OLX1CbM/edit#
