### ISSUE TITLE
A few E2E Conformance test cases have failed on the OpenShift cluster. 

### ISSUE THREAD

**Issue by Rouf111** [kubernetes-sigs/e2e-framework#329]
### What happened?

We ran the E2E Conformance test cases on OpenShift cluster OCP 4.12.13. Some of the below-highlighted tests Failed. 

- [It] [sig-network] DNS should provide DNS for the cluster [Conformance]
- [It] [sig-network] DNS should provide DNS for pods for Subdomain [Conformance]
- [It] [sig-network] DNS should provide DNS for services [Conformance]
- [It] [sig-network] Services should be able to change the type from ClusterIP to ExternalName [Conformance]
- [It] [sig-network] Services should be able to change the type from NodePort to ExternalName [Conformance]

While investigating, we observed that the `dns-querier-n` pod was unable to resolve a DNS name, despite the DNS record being available. 
`root@dns-querier-1:/# dig +notcp +noall +answer +search kubernetes.default.svc.cluster.local A`

We made some tweaks to the dig command, specifically by removing the `+search` option, and it worked fine. 
As a reference, please see the output of the below command, it was able to fetch the service name. 
`root@dns-querier-1:/# dig +notcp +noall +answer kubernetes.default.svc.cluster.local A`
`kubernetes.default.svc.cluster.local. 5    IN A    172.30.0.1`

**Note:**
We experienced this behavior on the OpenShift cluster only NOT on any other KubeADM setup. 

### What did you expect to happen?

The `+search` option in the dig command is used to append domains from the local domain search list; 
Since we are specifying the FQDN I think `+search` can be skipped. 

As we did notice after removing the `+search` option from the dig command it worked. 
Or 
We can have the option to try resolving the DNS with/without the `+search` option.

### How can we reproduce it (as minimally and precisely as possible)?

On the OCP cluster run the E2E conformance test for `[It] [sig-network] DNS should provide DNS for the cluster [Conformance]`
you will notice that the pods will be deployed and once the dig command starts it fails to resolve it.
tweak the dig command by removing `+search` option and then exec into the `dns-query` pod to manually run the command it will work.

### E2E Provider Used

kind

### `e2e-framework` Version

v1.25.8

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
$ uname -a
Linux master-0 4.18.0-372.51.1.rt7.208.el8_6.x86_64

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by harshanarayana** [comment]
@Rouf111 Thanks for reaching out to us here with a bug report. 

I went through the report and couldn't really identify how the reported issue relates to the `e2e-framework`. 

> We can have the option to try resolving the DNS with/without the +search option.

Would you be able to explain the requirements a bit more

**Comment by neolit123** [comment]
you'd have to talk to openshift about this.
log a ticket in the product support issue tracker and they will handle it, by replying to you and/or even sending fixes to kubernetes/kubernetes/test/... where the active framework of kubernetes is in use. the framework in this repo is the new framework, which is still not used in k/k.

/close
/kind support
