### ISSUE TITLE
Setup/Teardown run as subtest using provided name

### ISSUE THREAD

**Issue by phisco** [kubernetes-sigs/e2e-framework#333]
### What do you want to see?

At present, when multiple Setup or Teardown steps are defined, it can be challenging to identify which specific step has failed if the proper logs were not configured initially. This results from the fact that while Assessment steps are executed in dedicated subtests, Setup and Teardown steps are not. Actually, names for the Setup and Teardown steps are totally ignored, which I don't think was the desired behaviour. 

I think it could be useful to execute all steps in dedicated subtests.

**Comment by phisco** [comment]
Ping @vladimirvivien @harshanarayana given that I had your attention for the other issue 😬

**Comment by harshanarayana** [comment]
+1 to this. This will be a very useful change.

**Comment by harshanarayana** [comment]
@phisco Do you happen to have a possible format for these setup/teardowns in mind in terms of naming them ? If so, please share that here ?

**Comment by vladimirvivien** [comment]
@phisco I think it's a good idea to take a closer look how setup and teardown are put together. I don't see any harm in running them as subtests similar to other steps like "Assess".

**Comment by phisco** [comment]
Cool @vladimirvivien, I can give it a look over the holidays and try opening a PR for it!

**Comment by phisco** [comment]
I really need to find the time to work on this 😩 if anyone else wants to jump in, please do!

**Comment by vladimirvivien** [comment]
This is still relevant and needed.
