### ISSUE TITLE
Allow adding custom labels and annotations when creating namespace

### ISSUE THREAD

**Issue by Fricounet** [kubernetes-sigs/e2e-framework#364]
### What do you want to see?

Hello :wave: 
I was wondering if we could consider allowing to add user-defined labels and annotation when creating a namespace with [envfuncs.CreateNamespace](https://github.com/kubernetes-sigs/e2e-framework/blob/v0.3.0/pkg/envfuncs/ns_funcs.go#L38).

The feature request is motivated by the fact that in our case we use custom labels and annotations to configure behaviors of the namespace like cascade deletion of the namespace even if resources still exist in it, or adding metadata related to which feature is running in the namespace.
What do you think about it?

For the implementation, I think it could be easily added with an option pattern:
```
type CreateNamespaceOpts func(ns *corev1.Namespace)

func WithLabels(client klient.Client, labels map[string]string) CreateNamespaceOpts {
  return func(ns *corev1.Namespace) {
    client.Ressources.Labels(&ns, labels)
  }
}

func WithAnnotations(client klient.Client, annotations map[string]string) CreateNamespaceOpts {
	return func(ns *corev1.Namespace) {
		client.Ressources.Annotate(&ns, annotations)
	}
}

func CreateNamespace(name string, opts ...CreateNamespaceOpts) env.Func {
	return func(ctx context.Context, cfg *envconf.Config) (context.Context, error) {
		namespace := corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: name}}
		client, err := cfg.NewClient()
		if err != nil {
			return ctx, fmt.Errorf("create namespace func: %w", err)
		}
               for _, opt := range opts {
		        opt(client, &namespace)
	       }
		if err := client.Resources().Create(ctx, &namespace); err != nil {
			return ctx, fmt.Errorf("create namespace func: %w", err)
		}
		cfg.WithNamespace(name) // set env config default namespace
		return context.WithValue(ctx, namespaceContextKey(name), namespace), nil
	}
}
```

**Comment by harshanarayana** [comment]
@Fricounet  That sounds like a fair ask. Would you be willing to opening a PR for the same or do you want me to take a stab at it later today ?

**Comment by Fricounet** [comment]
Hey @harshanarayana I'd love to open a PR for this if that's fine with you :smile: 
I should be able to create the PR this week

**Comment by harshanarayana** [comment]
@Fricounet go head. 

/assign @Fricounet
