### ISSUE TITLE
Ambiguous call to `cfg.Client()` in `CreateClusterWithConfig` 

### ISSUE THREAD

**Issue by maximilianbraun** [kubernetes-sigs/e2e-framework#369]
### What happened?

For context: I'm implementing a custom provider and I was plying around with `CreateClusterWithConfig` and `CreateCluster`. I noticed panic with `CreateClusterWithConfig` resulting from the call to `cfg.Client()` [1] which expects a kubeconfig to be in the config before being set. There is no call to `cfg.Client()` before `cg.WithKubeConfigFile()` in `CreateCluster`.

[1]: https://github.com/kubernetes-sigs/e2e-framework/blob/main/pkg/envfuncs/provider_funcs.go#L84

### What did you expect to happen?

The call before initialization looks like a sideeffect. Not sure if it is wanted.

### How can we reproduce it (as minimally and precisely as possible)?

---

### E2E Provider Used

kind

### `e2e-framework` Version

0.3.0

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by reetasingh** [comment]
@maximilianbraun this looks like a bug since cfg.Client() function expects cfg.kubeconfig to be set before calling. Also the cfg.Client().RESTConfig() returns a restconfig which is not used anywhere. Happy to raise a PR to fix it
