### ISSUE TITLE
Why does `-parallel` and `-fail-fast` can't be used together?

### ISSUE THREAD

**Issue by Fricounet** [kubernetes-sigs/e2e-framework#385]
Hello :wave: 
I'm trying to understand why flags `-parallel` and `-fail-fast` can't be used together. I've looked at the [PR](https://github.com/kubernetes-sigs/e2e-framework/pull/118) that implemented the `fail-fast` but couldn't find a reason as to why they can't be used together. 
I'm asking because I've been using `-fail-fast` with `t.Parallel()` in my tests without running into any issue so I wonder what is different with `-parallel`?

**Comment by vladimirvivien** [comment]
@Fricounet 
Apologies for the delay.
So, you are saying that you can run tests with `--fail-fast` and call to `t.Parallel` but can't do it with `--parallel` flag ?
Do you get an error ?

**Comment by Fricounet** [comment]
@vladimirvivien no worries
Well the error I get when running `-fail-fast` and `parallel` is part of the framework itself. It is defined here https://github.com/kubernetes-sigs/e2e-framework/blob/main/pkg/flags/flags.go#L283

That's why I don't quite understand why :sweat_smile: I thought that maybe I'm just missing some context on why this decision was made initially

**Comment by vladimirvivien** [comment]
@Fricounet Looking at the code I think I remember why it was encoded like that.
Maybe the thinking was that if the framework is executing tests concurrently, fail-fast would have to be applied to all tests inflight and end the entire test run. Having that mutual exclusivity makes it easier to reason about.

If you have an idea that can make this better, you should definitely discuss here. Again, a lot of those decisions were done early on, so they may be due for a revisit.

**Comment by Fricounet** [comment]
@vladimirvivien What do you think about canceling the parent context if `fail-fast` is enabled? This way all currently running tests would have to stop too?

I can try to take a look and see if I can come up with a PR.
Thanks for the context anyway :)

**Comment by Fricounet** [comment]
@vladimirvivien yes! I'll try to work on this next week
