### ISSUE TITLE
Execute test features in parallel

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/e2e-framework#49]
Currently all tests are executed serially. This issue is to request that the framework also support parallel test execution.

> This originated from #17 

### Feature testing
A feature is considered to be a unit of testable logic in the code. As such, the step functions, that make up a feature, should always be executed in serial as a unit.  This guarantees predictable execution flow and predictable context propagation.

```go
TestFunc(t *testing.T){
    f := feature.New("my feature").Assess("check1", ...).Assess("check2"...).Feature()
    env.Test(f)
}
```
In the previous snippet, assessments "check1" and "check2" will be executed serially as part of the feature.

### Concurrent feature testing
A test function with multiple features, however, should be able to be exercised concurrently as shown below:

```go
    f0 := feature.New("my feature").Assess("check1", ...).Assess("check2"...).Feature()
    f1 := feature.New("my feature").Assess("check3", ...).Assess("check4"...).Feature()
    f2 := feature.New("my feature").Assess("check5", ...).Assess("check6"...).Feature()

    env.TestInParallel(f0, f1, f2)
```
Features f0, f1, f2 should be executed concurrently.

> Note `env.Test(f)` and `env.TestInParallel(f)` should be equivalent.

### Forcing concurrent execution
It is convenient to be able to force tests to be executed concurrently.  The code should support the ability to execute all tests in a package concurrently using an environment configuration.

This can be done programmatically as shown below:
```go
TestMain(m *testing.M){
    env  := env.NewWithConfig(envconfig.New().WithParallelTestEnabled())
}
```

Or driven by the `--parallel` flag, by creating the environment configuration from CLI flags as shown:

```go
TestMain(m *testing.M){
    env  := env.NewWithConfig(envconfig.NewFromFlags())
}
```
Then, tests are executed as

```
go test ./package -args --parallel
```

> When the configured for parallel testing `env.Test(f0, f1, f2)` and `env.TestInParallel(f0, f1, f2)` are equivalent

**Comment by harshanarayana** [comment]
@vladimirvivien Please assigning this one to me if someone is not already working on this? Let me make a PR with a prototype of this for review.
