### ISSUE TITLE
Question about test package layout

### ISSUE THREAD

**Issue by aledbf** [kubernetes-sigs/e2e-framework#50]
The examples in the repository only use one package (main) to contain `main_test` and the go files containing the tests.
What would be the suggested approach to use multiple packages?

from 
```shell
suites
│    featureset_test.go
│    filter_test.go
│    hello_test.go
│    main_test.go
```

to 
```shell
suites
│   main_test.go
│   hello_test.go 
│
└───somepackage
│   │   featureset_test.go
│   │   ...
│
└───other
│       │   filter_test.go
│       │   ...
``` 

In godog this is explicit, using `InitializeScenario`

**Comment by vladimirvivien** [comment]
@aledbf apologies for the late reply (this did not come up in my notifications).

This project leans on Go's testing framework and tools (in the stdlib) for features which means each package is tested separately. Having said that, I am not sure if using `TestMain` supports nested packages.  If it does, then your proposal would work. 

I am not familiar with godog.  It looks like it provides its own binary, which this project does not.

**Comment by aledbf** [comment]
@vladimirvivien thank you for the response. I end up having one TestMain per package. One of the downsides is you end up with multiple binaries (`go test -c`). If you just run the tests works just fine.
Thanks!
