### ISSUE TITLE
Introduce support for Waiting for given cluster conditions

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/e2e-framework#60]
As a test writer of components running on Kubernetes, it would be extremely useful to have the capability to wait for one or more cluster conditions before proceeding in the test.  

### A framework for Waiting
A new package `klient/wait` could be the starting point for an API to express conditions for waiting by leveraging the `wait` package in API machinery "k8s.io/apimachinery/pkg/util/wait"):

```go
package wait

func For(cond func() (bool, error)){...}
```
So, a test writer may have condition as follows:

```go
func TestSomething(t *testing.T){
    wait.For(t, func() (bool, error) {
        var ns coreV1.Namespace
        cfg.client.List(ns)
        ...
    )}
}
```

### Pre-defined conditions
The framework could have a collection of pre-defined conditions that can be used by test writers:

```go
func TestSomething(t *testing.T) {
   var pod coreV1.Pod
   wait.For(PodReadyCondition(pod))
}

**Comment by vladimirvivien** [comment]
@harshanarayana I missed that ping. Sorry.

**Comment by harshanarayana** [comment]
No worries @vladimirvivien Let me open a PR with some prototype for a feedback.

**Comment by harshanarayana** [comment]
@vladimirvivien I have opened a draft PR for the same. Hope the changes in there matches with what you had in mind for this behavior.
