### ISSUE TITLE
Dry run

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes-sigs/e2e-framework#62]
Supply a dry-run flag so we can check which tests would be run given the current flags.

**Comment by harshanarayana** [comment]
@johnSchnake  Are you still looking into this or I am free to take this up ?

**Comment by johnSchnake** [comment]
You can take it up; I don’t have the cycles right now.

**Comment by johnSchnake** [comment]
As a side note for this, my hope would be that this work would also enable the total number of tests to be run to be determined before any run.

This is important when sending progress updates so you can say things like: 3/99 tests completed. Otherwise you have no knowledge of how many tests will end up being targeted.

Ginkgo makes this available in a `suiteWillBegin` hook; hopefully we can get that same data available in one of our hooks.

**Comment by harshanarayana** [comment]
@johnSchnake  Sounds good. Let me put up a draft PR with the changes so that you and @vladimirvivien  can confirm if it is on the right path. Thanks 

// H

**Comment by harshanarayana** [comment]
@johnSchnake  Do we want to consider each assessment as a test and provide a `current/totalCount` output or the same output for `Testxxxx` of `testing.T` instead ?

`testing` package as far as I remember does not expose any public methods that we can use to get the total number of tests that are under `testing.M`. It has a private entity though.  It has a very handy `listTests` but that is private too.

**Comment by johnSchnake** [comment]
So I think this is one possible complication because different people may consider different things 'tests'.

Some people may see each `TestFoo` as a test, but each of those can include multiple features. Each feature may have multiple steps.

Ideally we could surface each of these but that definitely makes it harder. But now we do have the ability to filter tests based on test name and feature tag, so I think we have to surface those.

So I think it would be best to have something like:
```
TestsToBeRun: 8
FeaturesToBeRun: 11
AssessmentsToBeRun: 30
```

**Comment by harshanarayana** [comment]
@johnSchnake  All right. I do like that idea. Let me get that changes sorted. 

The other complication comes like you mentioned in #101  with `TestInParallel` when it comes to tracking the completed tests/features/assessments. Do we have a preference on how we want to track the number of completed items for corresponding bucket ?

**Comment by johnSchnake** [comment]
I think the parallel issue doesn't bother the counts much; it makes it a bit unpredictable which will finish when, but otherwise if you keep incrementing the counts `AfterEachFeature` or `AfterEachTest` you'd be fine.

**Comment by harshanarayana** [comment]
Sorry, been a bit behind on this PR. Will have this ready for review by EOW.
