### ISSUE TITLE
Prow issue where kind clusters are surviving into new test runs

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes-sigs/e2e-framework#67]
See https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_e2e-framework/63/pull-e2e-framework-test/1448431533592416256#1:build-log.txt%3A50

Just one cluster has been created, but when listing clusters there are numerous others already there.

These must have come from other runs.

May be related to #66 if it is an issue with how the hosts and being used.

**Comment by dims** [comment]
@johnSchnake isn't it being created here? https://github.com/kubernetes-sigs/e2e-framework/blob/main/klient/k8s/resources/main_test.go#L96

**Comment by johnSchnake** [comment]
https://medium.com/@xcoulon/how-to-avoid-parallel-execution-of-tests-in-golang-763d32d88eec describes exactly the same issue; tests werent in parallel but go was running packages in parallel causing racy behavior.

This also explains why I can't repro locally (different GOMAXPROCS set I'm assuming)

Should get a fix for this soon if all I have to do is change `-p 1`
