### ISSUE TITLE
Upgrade controller-runtime to latest version

### ISSUE THREAD

**Issue by jpmcb** [kubernetes-sigs/e2e-framework#86]
I noticed that the version of controller runtime used is [`v0.9.0`](https://github.com/kubernetes-sigs/e2e-framework/blob/main/go.mod)

Is it possible to bump this to a latter version of controller runtime? It seems that `v0.9.0` of controller runtime uses an older version of spf13/cobra which has a few security vulnerabilities (which aren't actually ever executed)

Happy to open a PR! Thanks much!

**Comment by vladimirvivien** [comment]
@jpmcb Happy to receive a PR if you 've got the bandwidth 😄

**Comment by cpanato** [comment]
I can work on that tomorrow if that is fine
