### ISSUE TITLE
k8s resource watcher implementation

### ISSUE THREAD

**Issue by ShwethaKumbla** [kubernetes-sigs/e2e-framework#97]
K8S object watchers are great functionality provided by k8s to get efficient change notifications on resources.
The events supported by these watchers are
1. ADD
2. MODIFY/UPDATE
3. DELETE

The idea here is to make developer implementation easier. Without knowing the resource core type of k8s objects they have to just register their actions/functions for respective watch events using the provision provided by this framework and to stay informed about when these events gets triggered, just use Watch() which resides inside klient/k8s/resources package.

## Proposal
Watch function accepts a `object ObjectList` as an argument. ObjectList type is used to inject the resource type in which Watch has to be applied.

`klient/k8s/resources/resources.go`
```go=
import (
    "sigs.k8s.io/controller-runtime/pkg/client"
    "k8s.io/apimachinery/pkg/watch"
)

func (r *Resources) Watch(ctx context.Context,object client.ObjectList, opts client.ListOptions) watch.Interface {
    cl, err := client.NewWithWatch(cfg, client.Options{})
    if err != nil {
        log.Println("error while creating a watcher client", err)
        return
    }
    
    watcher, err := cl.Watch(ctx, object, &ops) 
     if err != nil {
        log.Println("error while creating a watcher client", err)
        return nil, err
    }
    
    return watcher
}
```

Watch() in resources.go will return the `watcher` type which helps to call `InvokeEventHandler()`. InvokeEventHandler accepts `EventHandlerFuncs` which carries the user registered function sets.

file : klient/k8s/resources/watch.go

```go=
// InvokeEventHandler triggers the registered methods based on the event received for particular k8s resources.
func (watcher watch.Interface)InvokeEventHandler(f EventHandlerFuncs{}) {
    for {
	select {
	case event, ok := <-watcher.ResultChan():
            // retrieve the event type
            eventType := event.Type
        
            switch eventType {
            case watch.Added:
                f.Add(event.Object)
            case watch.Modified:
                f.Update(event.Object)
            case watch.Deleted:
                f.Delete(event.Object)
            }
        } 
        
    }
}


type EventHandlerFuncs struct {
	AddFunc    func(obj interface{})
	UpdateFunc func(obj interface{})
	DeleteFunc func(obj interface{})
}

func (e EventHandlerFuncs) Add(obj interface{}) {
	...
}

func (e EventHandlerFuncs) Update(newObj interface{}) {
	...
}


func (e EventHandlerFuncs) Delete(obj interface{}) {
	...
}
```

**Comment by helayoty** [comment]
I'd like to help implementing this feature if this is possible.
